#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
from selenium import webdriver
from selenium.webdriver.chrome.options import Options


chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(options=chrome_options)


def usage():
    print('''
            Dwiki - Download wikipedia articles for the CLI\n
            
            python Dwiki <query>

            Usage:
                    
            $ python Dwiki github  #Downloads the wikipedia article as a pdf
        ''')

input = sys.argv[1:]
args = (' '.join(input))

try:
    link = 'https://en.wikipedia.org/w/index.php?title=Special:ElectronPdf&page={}&action=show-download-screen'
    open = link.format(str(args))
    driver.get(open)
    driver.find_element_by_xpath("//html/body/div[3]/div[3]/div[3]/form/div/span/span/button").click()
    print("[+] PDF Downloaded..")
except KeyboardInterrupt:
        raise Exception('Download Interrupted..!')
        usage()
